```{r message=FALSE}
library(faraway)
library(dplyr)
library(ggplot2)

data(pima)
```

```{r}
pima %>% head()
summary(pima)
sort(pima$diastolic)
```

```{r}
pima$diastolic[pima$diastolic == 0] <- NA 
pima$glucose[pima$glucose == 0] <- NA
pima$triceps[pima$triceps == 0] <- NA
pima$insulin[pima$insulin == 0] <- NA
pima$bmi[pima$bmi == 0] <- NA
```

```{r}
pima$test <- factor(pima$test)
summary(pima$test)
```

```{r}
levels(pima$test) <- c("negative","positive")
summary(pima)
```

```{r}
hist(pima$diastolic)
ggplot(aes(x = diastolic), data = pima) + geom_histogram(binwidth = 10 )
```

```{r}
plot(density(pima$diastolic,na.rm=TRUE))
plot(sort(pima$diastolic),pch=".")
plot(diabetes ~  diastolic,pima)
plot(diabetes ~  test,pima)

pairs(pima)
?pairs
```

```{r}
data(stat500)
stat500 <- data.frame(scale(stat500)) 
plot(final ~  midterm,stat500)
abline(0,1)

g <- lm(final ~ midterm,stat500) 
abline(g$coef,lty=5)
cor(stat500)
```

```{r}
data(gala)
gala %>% head()

gfit <- lm(Species ~ Area + Elevation + Nearest + Scruz + Adjacent, data=gala)
summary(gfit)

x <- cbind(1,gala[,-c(1,2)])
y <- gala$Species

x <- as.matrix(x)
t(x) %*% x

xtxi <- solve(t(x) %*% x)

gfit <- lm(Species ~  Area + Elevation + Nearest + Scruz + Adjacent, data=gala)
gs <- summary(gfit) 
gs$cov.unscaled

?solve
```

```{r}
x = cbind(c(1,2,3), c(0,5, 1))
y = cbind(c(4,2,0), c(0.5,5, 1))

x  +y

cbind(c(1,2,3), c(0,5,1)) * 3
cbind(c(4,6), c(0,3)) / 4

3 * cbind(c(1,4,2)) + cbind(c(0, 0, 5)) - cbind(c(3,0,2)) / 3

   
rbind(c(1,2,1,5), c(0,3,0,4),c(-1,-2,0,0)) %*%
  cbind(c(1,3,2,1))

cbind(c(1,1,1,1), c(2104,1416,1534,852)) %*% 
  cbind(c(-40,0.25))

rbind(c(1,3,2), c(4,0,1)) %*%
  cbind(c(1,0,5), c(3,1,2))

cbind(c(1,2), c(3,5)) %*%
  cbind(c(0,3), c(1,2))


```

```{r}
g <- lm(Species ~ Area+Elevation+Nearest+Scruz+Adjacent,data=gala)


x0 = c(1,0.08,93,6.0,12.0,0.34)
g$coef 
y0 = sum(t(x0)*g$coef)

x <- cbind(1,gala[,3:7])
x <- as.matrix(x)
xtxi <- solve(t(x) %*% x)


bm <- sqrt(x0 %*% xtxi %*% x0) *2.064 * 60.98

```